version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Database configuration
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@db:5432/ragdb}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5432}
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD:-password}
      - PGDATABASE=${PGDATABASE:-ragdb}
      
      # API Keys (set these in production)
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      
      # Replit environment (for compatibility)
      - REPLIT_DEV_DOMAIN=${DOMAIN:-localhost:5000}
    volumes:
      - chroma_data:/app/data/chroma
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${PGDATABASE:-ragdb}
      - POSTGRES_USER=${PGUSER:-postgres}
      - POSTGRES_PASSWORD=${PGPASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  chroma_data: